import type { ScenarioRecord } from '@/lib/domain/types'

export const scenarioCatalog: ScenarioRecord[] = [
  {
    id: 'property-fast-track',
    team: 'Teams',
    title: 'Property Fast-Track',
    status: 'ready',
    environment: 'production',
    description:
      'FNOL, triage, documents, approval, and vendor dispatch stitched together from agents, MCP tools, and workflow gates.',
    updatedLabel: 'App-owned scenario catalog',
    agents: 7,
    mcps: 4,
    workflows: 5,
    servicesOnline: 7,
    totalServices: 7,
    previewServices: [
      { id: 'preview-1', label: 'Rachel', icon: 'phone', accent: 'violet' },
      { id: 'preview-2', label: 'Atlas', icon: 'shield', accent: 'blue' },
      { id: 'preview-3', label: 'Docling', icon: 'file', accent: 'blue' },
      { id: 'preview-4', label: 'Hermes', icon: 'sparkles', accent: 'orange' },
      { id: 'preview-5', label: 'Adjuster', icon: 'wrench', accent: 'orange' },
      { id: 'preview-6', label: 'Northside', icon: 'truck', accent: 'green' },
    ],
    stages: [
      { id: 'notify', title: '01 · Notify · FNOL · intake', x: 336, y: 214, width: 286, height: 242 },
      { id: 'triage', title: '02 · Triage · severity · reserves', x: 660, y: 118, width: 302, height: 430 },
      { id: 'docs', title: '03 · Docs · evidence · enrichment', x: 1000, y: 98, width: 286, height: 268 },
      { id: 'dispatch', title: '04 · Dispatch · vendor · booking', x: 1318, y: 126, width: 324, height: 392 },
    ],
    nodes: [
      {
        id: 'presenter',
        kind: 'endpoint',
        title: 'Presenter',
        subtitle: 'Insured side',
        description: 'Reports the loss on behalf of Meridian Logistics.',
        icon: 'user',
        accent: 'green',
        status: 'ready',
        liveStatus: 'ready',
        x: 20,
        y: 260,
        width: 220,
        height: 136,
      },
      {
        id: 'vendor-endpoint',
        kind: 'endpoint',
        title: 'Northside Dispatch',
        subtitle: 'Vendor side',
        description: 'Confirms ETA on the mitigation team deployment.',
        icon: 'truck',
        accent: 'green',
        status: 'ready',
        liveStatus: 'ready',
        x: 1720,
        y: 258,
        width: 232,
        height: 136,
      },
      {
        id: 'notify-intake',
        kind: 'agent',
        title: 'Rachel · FNOL Intake',
        subtitle: 'ElevenLabs · correction',
        description: 'Captures FNOL, reads schema, and confirms consent.',
        icon: 'phone',
        accent: 'violet',
        status: 'inactive',
        liveStatus: 'running',
        x: 22,
        y: 60,
        width: 242,
        height: 132,
        parentId: 'notify',
        metrics: ['€0.00', 'u0', '8s'],
      },
      {
        id: 'atlas-triage',
        kind: 'agent',
        title: 'Atlas · Triage Module',
        subtitle: 'n8n · weather · property',
        description: 'Scores severity from weather, roof type, and exposure.',
        icon: 'shield',
        accent: 'blue',
        status: 'inactive',
        liveStatus: 'ready',
        x: 24,
        y: 42,
        width: 248,
        height: 138,
        parentId: 'triage',
        metrics: ['€0.00', 'u0', '9s'],
      },
      {
        id: 'reserve-gate',
        kind: 'agent',
        title: 'Rachel · Reserve Gate',
        subtitle: 'Human approval · reserve threshold',
        description: 'Routes the claim and opens the reserve approval gate.',
        icon: 'brain',
        accent: 'violet',
        status: 'inactive',
        liveStatus: 'review',
        x: 24,
        y: 210,
        width: 248,
        height: 128,
        parentId: 'triage',
        metrics: ['€0.00', 'u0', '5s'],
      },
      {
        id: 'doc-check',
        kind: 'agent',
        title: 'Docling · Doc Check',
        subtitle: 'document-service · extract',
        description: 'Extracts policy pages and flags evidence gaps.',
        icon: 'file',
        accent: 'blue',
        status: 'inactive',
        liveStatus: 'ready',
        x: 24,
        y: 40,
        width: 238,
        height: 126,
        parentId: 'docs',
        metrics: ['€0.00', 'u0', '8s'],
      },
      {
        id: 'human-review',
        kind: 'agent',
        title: 'Hermes · Handler Copilot',
        subtitle: 'Chatwoot-side · LLM review',
        description: 'Packages the dossier for adjuster review and approval.',
        icon: 'sparkles',
        accent: 'orange',
        status: 'inactive',
        liveStatus: 'review',
        x: 24,
        y: 186,
        width: 238,
        height: 126,
        parentId: 'docs',
        metrics: ['€0.00', 'u0', '6s'],
      },
      {
        id: 'adjuster',
        kind: 'agent',
        title: 'Adjuster Copilot',
        subtitle: 'n8n · dossier compile',
        description: 'Compiles a mitigation dossier for human sign-off.',
        icon: 'wrench',
        accent: 'orange',
        status: 'inactive',
        liveStatus: 'review',
        x: 24,
        y: 52,
        width: 272,
        height: 130,
        parentId: 'dispatch',
        metrics: ['€0.00', 'u0', '8s'],
      },
      {
        id: 'vendor-outreach',
        kind: 'agent',
        title: 'Harry · Vendor Outreach',
        subtitle: 'ElevenLabs outbound',
        description: 'Calls Northside for ETA confirmation and dispatch.',
        icon: 'tower',
        accent: 'violet',
        status: 'inactive',
        liveStatus: 'ready',
        x: 24,
        y: 214,
        width: 272,
        height: 118,
        parentId: 'dispatch',
        metrics: ['€0.00', 'u0', '9s'],
      },
    ],
    edges: [
      { id: 'e1', source: 'presenter', target: 'notify-intake', live: true },
      { id: 'e2', source: 'notify-intake', target: 'atlas-triage', live: true },
      { id: 'e3', source: 'atlas-triage', target: 'reserve-gate', live: true },
      { id: 'e4', source: 'reserve-gate', target: 'doc-check', live: true },
      { id: 'e5', source: 'doc-check', target: 'human-review', live: true },
      { id: 'e6', source: 'human-review', target: 'adjuster', live: true },
      { id: 'e7', source: 'adjuster', target: 'vendor-outreach', live: true },
      { id: 'e8', source: 'vendor-outreach', target: 'vendor-endpoint', live: true },
    ],
    activity: [
      {
        id: 'a1',
        label: 'Catalog loaded',
        detail: 'Scenario graph was loaded through the app-owned repository instead of browser patch metadata.',
        time: '21:04',
      },
      {
        id: 'a2',
        label: 'Reserve gate armed',
        detail: 'Reserve approval is waiting on human review after triage severity exceeded threshold.',
        time: '21:09',
      },
      {
        id: 'a3',
        label: 'Dispatch ready',
        detail: 'Vendor outreach is staged with Northside Dispatch and the slot recommendation payload.',
        time: '21:12',
      },
    ],
    dockLabel: 'LIVE MCP CONTROL',
    detailSummary:
      'This starter turns the old Property Fast-Track patch flow into a real app-owned workspace: one dashboard, one scenario canvas, one backend boundary.',
  },
  {
    id: 'motor-fleet',
    team: 'Teams',
    title: 'Motor Fleet',
    status: 'running',
    environment: 'production',
    description:
      'Telematics-triggered claims, repair approval, and body shop dispatch for commercial fleet incidents.',
    updatedLabel: 'App-owned fleet path',
    agents: 5,
    mcps: 3,
    workflows: 4,
    servicesOnline: 5,
    totalServices: 5,
    previewServices: [
      { id: 'fleet-1', label: 'Rachel', icon: 'phone', accent: 'violet' },
      { id: 'fleet-2', label: 'Atlas', icon: 'shield', accent: 'blue' },
      { id: 'fleet-3', label: 'Liam', icon: 'truck', accent: 'green' },
      { id: 'fleet-4', label: 'Hermes', icon: 'sparkles', accent: 'orange' },
    ],
    stages: [
      { id: 'fleet-intake', title: '01 · Intake · telematics', x: 340, y: 182, width: 288, height: 228 },
      { id: 'fleet-triage', title: '02 · Damage · repair gate', x: 670, y: 122, width: 302, height: 338 },
      { id: 'fleet-dispatch', title: '03 · Body shop · dispatch', x: 1022, y: 148, width: 320, height: 298 },
    ],
    nodes: [
      {
        id: 'fleet-driver',
        kind: 'endpoint',
        title: 'Driver',
        subtitle: 'Telematics side',
        description: 'Vehicle sends the initial incident and location payload.',
        icon: 'user',
        accent: 'green',
        status: 'ready',
        liveStatus: 'ready',
        x: 28,
        y: 248,
        width: 220,
        height: 136,
      },
      {
        id: 'fleet-shop',
        kind: 'endpoint',
        title: 'Preferred Body Shop',
        subtitle: 'Vendor side',
        description: 'Accepts the repair booking and confirms intake.',
        icon: 'truck',
        accent: 'green',
        status: 'ready',
        liveStatus: 'ready',
        x: 1410,
        y: 248,
        width: 232,
        height: 136,
      },
      {
        id: 'fleet-rachel',
        kind: 'agent',
        title: 'Rachel · FNOL Intake',
        subtitle: 'Telematics event intake',
        description: 'Translates the incident payload into a repair claim.',
        icon: 'phone',
        accent: 'violet',
        status: 'ready',
        liveStatus: 'running',
        x: 24,
        y: 54,
        width: 244,
        height: 126,
        parentId: 'fleet-intake',
        metrics: ['€0.00', 'u0', '6s'],
      },
      {
        id: 'fleet-atlas',
        kind: 'agent',
        title: 'Atlas · Collision Scoring',
        subtitle: 'Damage and drivable estimation',
        description: 'Combines telematics and prior repair history into a severity score.',
        icon: 'shield',
        accent: 'blue',
        status: 'ready',
        liveStatus: 'ready',
        x: 24,
        y: 48,
        width: 248,
        height: 126,
        parentId: 'fleet-triage',
        metrics: ['€0.00', 'u0', '7s'],
      },
      {
        id: 'fleet-review',
        kind: 'agent',
        title: 'Hermes · Repair Approval',
        subtitle: 'Human review with recommendation',
        description: 'Queues adjuster sign-off before the shop booking goes out.',
        icon: 'sparkles',
        accent: 'orange',
        status: 'review',
        liveStatus: 'review',
        x: 24,
        y: 198,
        width: 248,
        height: 112,
        parentId: 'fleet-triage',
        metrics: ['€0.00', 'u0', '4s'],
      },
      {
        id: 'fleet-liam',
        kind: 'agent',
        title: 'Liam · Repair Dispatch',
        subtitle: 'Shop scheduling agent',
        description: 'Books the selected partner and relays the repair slot.',
        icon: 'truck',
        accent: 'green',
        status: 'ready',
        liveStatus: 'running',
        x: 24,
        y: 62,
        width: 272,
        height: 126,
        parentId: 'fleet-dispatch',
        metrics: ['€0.00', 'u0', '9s'],
      },
    ],
    edges: [
      { id: 'f1', source: 'fleet-driver', target: 'fleet-rachel', live: true },
      { id: 'f2', source: 'fleet-rachel', target: 'fleet-atlas', live: true },
      { id: 'f3', source: 'fleet-atlas', target: 'fleet-review', live: true },
      { id: 'f4', source: 'fleet-review', target: 'fleet-liam', live: true },
      { id: 'f5', source: 'fleet-liam', target: 'fleet-shop', live: true },
    ],
    activity: [
      {
        id: 'f-a1',
        label: 'Telematics packet opened',
        detail: 'The incident payload was normalized with VIN, postal code, and drivable flag.',
        time: '21:02',
      },
      {
        id: 'f-a2',
        label: 'Repair approval pending',
        detail: 'Hermes has the recommended reserve and selected partner.',
        time: '21:10',
      },
    ],
    dockLabel: 'LIVE FLEET CONTROL',
    detailSummary:
      'The fleet path stays faithful to the earlier scenario workspace, but it now runs behind real route handlers and a reusable run model.',
  },
  {
    id: 'cargo-recovery',
    team: 'Teams',
    title: 'Cargo Recovery',
    status: 'review',
    environment: 'staging',
    description:
      'A lighter scenario showing how the platform can handle additional scenario families without changing the layout grammar.',
    updatedLabel: 'Template-ready extension scenario',
    agents: 4,
    mcps: 2,
    workflows: 3,
    servicesOnline: 3,
    totalServices: 4,
    previewServices: [
      { id: 'cargo-1', label: 'Beacon', icon: 'tower', accent: 'cyan' },
      { id: 'cargo-2', label: 'Ledger', icon: 'database', accent: 'blue' },
      { id: 'cargo-3', label: 'Helm', icon: 'bot', accent: 'orange' },
    ],
    stages: [
      { id: 'cargo-intake', title: '01 · Intake · shipment alert', x: 378, y: 200, width: 308, height: 228 },
      { id: 'cargo-review', title: '02 · Evidence · recovery ops', x: 742, y: 132, width: 320, height: 308 },
    ],
    nodes: [
      {
        id: 'cargo-broker',
        kind: 'endpoint',
        title: 'Broker',
        subtitle: 'Partner side',
        description: 'Provides shipment context and delivery commitments.',
        icon: 'user',
        accent: 'green',
        status: 'ready',
        liveStatus: 'ready',
        x: 72,
        y: 252,
        width: 220,
        height: 136,
      },
      {
        id: 'cargo-beacon',
        kind: 'agent',
        title: 'Beacon · Intake',
        subtitle: 'Shipment incident capture',
        description: 'Starts the cargo recovery case and requests evidence.',
        icon: 'tower',
        accent: 'cyan',
        status: 'ready',
        liveStatus: 'running',
        x: 24,
        y: 56,
        width: 248,
        height: 126,
        parentId: 'cargo-intake',
        metrics: ['€0.00', 'u0', '5s'],
      },
      {
        id: 'cargo-ledger',
        kind: 'agent',
        title: 'Ledger · Evidence Graph',
        subtitle: 'MCP-backed recovery context',
        description: 'Combines manifests, photos, and carrier notes into one dossier.',
        icon: 'database',
        accent: 'blue',
        status: 'review',
        liveStatus: 'review',
        x: 24,
        y: 54,
        width: 266,
        height: 126,
        parentId: 'cargo-review',
        metrics: ['€0.00', 'u0', '6s'],
      },
      {
        id: 'cargo-helm',
        kind: 'agent',
        title: 'Helm · Recovery Ops',
        subtitle: 'Coordinator',
        description: 'Coordinates the partner follow-up and reserve recommendation.',
        icon: 'bot',
        accent: 'orange',
        status: 'inactive',
        liveStatus: 'ready',
        x: 24,
        y: 198,
        width: 266,
        height: 100,
        parentId: 'cargo-review',
        metrics: ['€0.00', 'u0', '7s'],
      },
    ],
    edges: [
      { id: 'c1', source: 'cargo-broker', target: 'cargo-beacon', live: true },
      { id: 'c2', source: 'cargo-beacon', target: 'cargo-ledger', live: true },
      { id: 'c3', source: 'cargo-ledger', target: 'cargo-helm', live: true },
    ],
    activity: [
      {
        id: 'c-a1',
        label: 'Evidence request drafted',
        detail: 'Carrier manifest and photo requests are queued for partner follow-up.',
        time: '20:58',
      },
    ],
    dockLabel: 'RECOVERY CONTROL',
    detailSummary:
      'This lightweight scenario proves the template can add more families without rewriting the dashboard or the canvas primitives.',
  },
]

export function getScenarioById(scenarioId: string) {
  return scenarioCatalog.find((scenario) => scenario.id === scenarioId)
}
