#!/usr/bin/env python3
"""
designqa Linear sync — idempotent upsert of a frontend feature issue.

Creates or updates a Linear issue keyed by surface slug + sprint label.
Attaches: Figma frame URL, acceptance criteria from sprint doc, screenshot links, a11y summary.

Usage:
    python3 linear_sync.py \
        --surface    canvas \
        --sprint     8 \
        --verdict    PASS-WITH-NOTES \
        --figma-url  "https://www.figma.com/design/..." \
        --report-md  docs/designqa-reports/2026-05-04--canvas/report.md \
        --axe-json   /tmp/designqa-2026-05-04/axe.json \
        --sprint-doc docs/sprints/sprint-8-scenario-builder-synthdata-factory.md

Environment:
    LINEAR_API_KEY — read from env or .env.local
"""
import sys, os, json, pathlib, argparse, urllib.request, urllib.parse, re


LINEAR_ENDPOINT = "https://api.linear.app/graphql"
TEAM_KEY = "AXA"


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    env_file = pathlib.Path(__file__).parents[4] / ".env.local"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    env.update({k: v for k, v in os.environ.items() if k.startswith("LINEAR")})
    return env


def gql(api_key: str, query: str, variables: dict | None = None) -> dict:
    body = json.dumps({"query": query, "variables": variables or {}}).encode()
    req = urllib.request.Request(
        LINEAR_ENDPOINT,
        data=body,
        headers={"Authorization": api_key, "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def get_team_id(api_key: str) -> str:
    data = gql(api_key, "{ teams { nodes { id key } } }")
    for team in data["data"]["teams"]["nodes"]:
        if team["key"] == TEAM_KEY:
            return team["id"]
    raise ValueError(f"Team '{TEAM_KEY}' not found in Linear workspace")


def get_backlog_state_id(api_key: str, team_id: str) -> str:
    data = gql(api_key, """
    query($filter: WorkflowStateFilter) {
      workflowStates(filter: $filter) { nodes { id name type } }
    }
    """, {"filter": {"team": {"id": {"eq": team_id}}}})
    for state in data["data"]["workflowStates"]["nodes"]:
        if state["type"] == "backlog":
            return state["id"]
    # Fall back to first unstarted state
    for state in data["data"]["workflowStates"]["nodes"]:
        if state["type"] == "unstarted":
            return state["id"]
    raise ValueError("No backlog/unstarted state found")


def find_existing_issue(api_key: str, team_id: str, label_filter: str) -> dict | None:
    """Find an existing designqa issue by its unique label e.g. 'designqa-canvas-sprint-8'."""
    data = gql(api_key, """
    query($filter: IssueFilter) {
      issues(filter: $filter, first: 5) {
        nodes { id identifier title url state { name } }
      }
    }
    """, {"filter": {
        "team": {"id": {"eq": team_id}},
        "title": {"containsIgnoreCase": label_filter},
    }})
    nodes = data["data"]["issues"]["nodes"]
    return nodes[0] if nodes else None


def extract_acs(sprint_doc_text: str) -> list[str]:
    return re.findall(r"- \[ \] .+", sprint_doc_text)[:15]


def build_issue_body(args, axe_data: dict | None, acs: list[str], report_path: str) -> str:
    verdict_emoji = {"PASS": "✅", "PASS-WITH-NOTES": "🟡", "FAIL": "🔴"}.get(args.verdict, "⏳")
    lines = [
        f"## DesignQA — Sprint {args.sprint} · {args.surface}",
        "",
        f"**Verdict:** {verdict_emoji} {args.verdict}",
        "",
        "## Figma",
        f"[Open in Figma]({args.figma_url})" if args.figma_url else "_Figma URL not yet available_",
        "",
        "## Acceptance Criteria",
    ]
    if acs:
        lines += acs
    else:
        lines.append("_Extract from sprint doc — see linked doc._")

    if axe_data:
        sc = axe_data.get("serious_critical", 0)
        adv = axe_data.get("advisory", 0)
        lines += [
            "",
            "## A11y Summary",
            f"- Serious/critical: {sc}",
            f"- Advisory: {adv}",
        ]

    lines += [
        "",
        "## QA Evidence",
        f"- Report: `{report_path}`",
        "_Screenshot links in report.md_",
        "",
        f"_Auto-generated by `designqa/tools/linear_sync.py`._",
    ]
    return "\n".join(lines)


def upsert_issue(api_key: str, team_id: str, state_id: str, args, axe_data, acs, report_path) -> dict:
    title = f"Sprint {args.sprint} — Frontend — {args.surface} (designqa)"
    body = build_issue_body(args, axe_data, acs, report_path)

    # Check for existing
    existing = find_existing_issue(api_key, team_id, f"designqa-{args.surface}-sprint-{args.sprint}")

    if existing:
        issue_id = existing["id"]
        result = gql(api_key, """
        mutation UpdateIssue($id: String!, $input: IssueUpdateInput!) {
          issueUpdate(id: $id, input: $input) {
            success issue { id identifier title url }
          }
        }
        """, {"id": issue_id, "input": {"title": title, "description": body}})
        issue = result["data"]["issueUpdate"]["issue"]
        print(f"Updated issue: {issue['identifier']} {issue['url']}")
    else:
        result = gql(api_key, """
        mutation CreateIssue($input: IssueCreateInput!) {
          issueCreate(input: $input) {
            success issue { id identifier title url }
          }
        }
        """, {"input": {
            "teamId": team_id,
            "stateId": state_id,
            "title": title,
            "description": body,
            "labelIds": [],
        }})
        issue = result["data"]["issueCreate"]["issue"]
        print(f"Created issue: {issue['identifier']} {issue['url']}")

    return issue


def write_payload(args, acs: list[str], axe_data: dict | None, report_path: str, out_dir: pathlib.Path):
    """Write payload markdown for manual runner when no API key available."""
    import datetime
    date_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    slug = f"designqa-{args.surface}-sprint-{args.sprint}"
    out_dir.mkdir(parents=True, exist_ok=True)
    body = build_issue_body(args, axe_data, acs, report_path)
    out_path = out_dir / f"{date_str}--{slug}.md"
    out_path.write_text(f"# Linear Issue Payload\n\n**Title:** Sprint {args.sprint} — Frontend — {args.surface} (designqa)\n\n{body}")
    print(f"Payload → {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Sync designqa results to a Linear frontend issue")
    parser.add_argument("--surface", required=True)
    parser.add_argument("--sprint", required=True)
    parser.add_argument("--verdict", default="PENDING-CRITIQUE")
    parser.add_argument("--figma-url", default=None)
    parser.add_argument("--report-md", default=None)
    parser.add_argument("--axe-json", default=None)
    parser.add_argument("--sprint-doc", default=None)
    parser.add_argument("--payload-dir", default="docs/qa", help="Fallback payload output dir")
    args = parser.parse_args()

    axe_data: dict | None = None
    if args.axe_json and pathlib.Path(args.axe_json).exists():
        axe_data = json.loads(pathlib.Path(args.axe_json).read_text())

    sprint_doc_text = ""
    if args.sprint_doc and pathlib.Path(args.sprint_doc).exists():
        sprint_doc_text = pathlib.Path(args.sprint_doc).read_text()
    acs = extract_acs(sprint_doc_text)

    report_path = args.report_md or "docs/designqa-reports/(see latest run)"

    env = load_env()
    api_key = env.get("LINEAR_API_KEY")

    if not api_key:
        print("LINEAR_API_KEY not set — writing payload for manual import.")
        write_payload(args, acs, axe_data, report_path, pathlib.Path(args.payload_dir))
        return

    try:
        team_id = get_team_id(api_key)
        state_id = get_backlog_state_id(api_key, team_id)
        upsert_issue(api_key, team_id, state_id, args, axe_data, acs, report_path)
    except Exception as e:
        print(f"Linear API error: {e} — writing payload instead.")
        write_payload(args, acs, axe_data, report_path, pathlib.Path(args.payload_dir))
        sys.exit(1)


if __name__ == "__main__":
    main()
